package pqt.dss.bor.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 27 16:09:28 PKT 2016
// ---------------------------------------------------------------------
public interface DssBranchOpenReqHeaderView extends ViewObject {
    void setNVC_wfDocumentId(oracle.jbo.domain.Number value);

    void borSearchUser();
}

