package pqt.dss.bor.model.eo;

import java.math.BigDecimal;

import java.sql.SQLException;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 16 19:14:37 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssBranchOpenReqCompanyImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BranchOpenReqIdFk,
        CompanyIdFk,
        Value,
        UserIdFk,
        EnterDate,
        LastUpdatedBy,
        LastUpdatedDate,
        BranchOpenReqCompIdPk,
        DssBranchOpenReqHeader;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BRANCHOPENREQIDFK = AttributesEnum.BranchOpenReqIdFk.index();
    public static final int COMPANYIDFK = AttributesEnum.CompanyIdFk.index();
    public static final int VALUE = AttributesEnum.Value.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int BRANCHOPENREQCOMPIDPK = AttributesEnum.BranchOpenReqCompIdPk.index();
    public static final int DSSBRANCHOPENREQHEADER = AttributesEnum.DssBranchOpenReqHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssBranchOpenReqCompanyImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("pqt.dss.bor.model.eo.DssBranchOpenReqCompany");
    }


    /**
     * Gets the attribute value for BranchOpenReqIdFk, using the alias name BranchOpenReqIdFk.
     * @return the value of BranchOpenReqIdFk
     */
    public Number getBranchOpenReqIdFk() {
        return (Number) getAttributeInternal(BRANCHOPENREQIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for BranchOpenReqIdFk.
     * @param value value to set the BranchOpenReqIdFk
     */
    public void setBranchOpenReqIdFk(Number value) {
        setAttributeInternal(BRANCHOPENREQIDFK, value);
    }

    /**
     * Gets the attribute value for CompanyIdFk, using the alias name CompanyIdFk.
     * @return the value of CompanyIdFk
     */
    public Number getCompanyIdFk() {
        return (Number) getAttributeInternal(COMPANYIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyIdFk.
     * @param value value to set the CompanyIdFk
     */
    public void setCompanyIdFk(Number value) {
        setAttributeInternal(COMPANYIDFK, value);
    }

    /**
     * Gets the attribute value for Value, using the alias name Value.
     * @return the value of Value
     */
    public Number getValue() {
        return (Number) getAttributeInternal(VALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Value.
     * @param value value to set the Value
     */
    public void setValue(Number value) {
        setAttributeInternal(VALUE, value);
    }

    /**
     * Gets the attribute value for UserIdFk, using the alias name UserIdFk.
     * @return the value of UserIdFk
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserIdFk.
     * @param value value to set the UserIdFk
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for EnterDate, using the alias name EnterDate.
     * @return the value of EnterDate
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnterDate.
     * @param value value to set the EnterDate
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for BranchOpenReqCompIdPk, using the alias name BranchOpenReqCompIdPk.
     * @return the value of BranchOpenReqCompIdPk
     */
    public Number getBranchOpenReqCompIdPk() {
        return (Number) getAttributeInternal(BRANCHOPENREQCOMPIDPK);
    }

    /**
     * Sets <code>value</code> as the attribute value for BranchOpenReqCompIdPk.
     * @param value value to set the BranchOpenReqCompIdPk
     */
    public void setBranchOpenReqCompIdPk(Number value) {
        setAttributeInternal(BRANCHOPENREQCOMPIDPK, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public DssBranchOpenReqHeaderImpl getDssBranchOpenReqHeader() {
        return (DssBranchOpenReqHeaderImpl) getAttributeInternal(DSSBRANCHOPENREQHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setDssBranchOpenReqHeader(DssBranchOpenReqHeaderImpl value) {
        setAttributeInternal(DSSBRANCHOPENREQHEADER, value);
    }


    /**
     * @param branchOpenReqCompIdPk key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number branchOpenReqCompIdPk) {
        return new Key(new Object[] { branchOpenReqCompIdPk });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
     protected void create(AttributeList attributeList) {
         super.create(attributeList);
         Date currentDate = new Date();
         setEnterDate((Date) currentDate.getCurrentDate());
         setLastUpdatedDate((Date) currentDate.getCurrentDate());
         SequenceImpl seq = new SequenceImpl("DSS_BRANCH_OPEN_REQ_COMP_SEQ", getDBTransaction());
         setBranchOpenReqCompIdPk(seq.getSequenceNumber());
         
//         setBranchStatus("INCOMPLETE");
//         setDssStatus("INCOMPLETE");
         
         FacesContext fctx = FacesContext.getCurrentInstance();
         ExternalContext ectx = fctx.getExternalContext();
         HttpSession userSession = (HttpSession) ectx.getSession(false);
         try {
             setUserIdFk(new Number(userSession.getAttribute("pUserId")));
             setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
         } catch (SQLException ex) {
             setUserIdFk(new Number(0));
             setLastUpdatedBy(new Number(0));
         }
     }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Date currentDate = new Date();
        if (operation == DML_UPDATE) {
            setLastUpdatedDate((Date) currentDate.getCurrentDate());
            FacesContext fctx = FacesContext.getCurrentInstance();
            ExternalContext ectx = fctx.getExternalContext();
            HttpSession userSession = (HttpSession) ectx.getSession(false);
            try {
                setUserIdFk(new Number(userSession.getAttribute("pUserId")));
                setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
            } catch (SQLException ex) {
                setUserIdFk(new Number(0));
                setLastUpdatedBy(new Number(0));
            }
        }
        super.doDML(operation, e);
    }
}

