package pqt.dss.bor.model.eo;

import java.math.BigDecimal;

import java.sql.SQLException;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 28 14:57:01 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssBranchOpenReqLineImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BrOpenReqLineIdPk,
        BrOpenReqHeaderFk,
        Years,
        UserIdFk,
        EnterDate,
        LastUpdatedBy,
        LastUpdatedDate,
        Rh,
        Zh,
        Sgh,
        Gh,
        Buh,
        Uh,
        Consultantans,
        Total,
        DssBranchOpenReqHeader;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BROPENREQLINEIDPK = AttributesEnum.BrOpenReqLineIdPk.index();
    public static final int BROPENREQHEADERFK = AttributesEnum.BrOpenReqHeaderFk.index();
    public static final int YEARS = AttributesEnum.Years.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int RH = AttributesEnum.Rh.index();
    public static final int ZH = AttributesEnum.Zh.index();
    public static final int SGH = AttributesEnum.Sgh.index();
    public static final int GH = AttributesEnum.Gh.index();
    public static final int BUH = AttributesEnum.Buh.index();
    public static final int UH = AttributesEnum.Uh.index();
    public static final int CONSULTANTANS = AttributesEnum.Consultantans.index();
    public static final int TOTAL = AttributesEnum.Total.index();
    public static final int DSSBRANCHOPENREQHEADER = AttributesEnum.DssBranchOpenReqHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssBranchOpenReqLineImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("pqt.dss.bor.model.eo.DssBranchOpenReqLine");
    }


    /**
     * Gets the attribute value for BrOpenReqLineIdPk, using the alias name BrOpenReqLineIdPk.
     * @return the value of BrOpenReqLineIdPk
     */
    public Number getBrOpenReqLineIdPk() {
        return (Number) getAttributeInternal(BROPENREQLINEIDPK);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrOpenReqLineIdPk.
     * @param value value to set the BrOpenReqLineIdPk
     */
    public void setBrOpenReqLineIdPk(Number value) {
        setAttributeInternal(BROPENREQLINEIDPK, value);
    }

    /**
     * Gets the attribute value for BrOpenReqHeaderFk, using the alias name BrOpenReqHeaderFk.
     * @return the value of BrOpenReqHeaderFk
     */
    public Number getBrOpenReqHeaderFk() {
        return (Number) getAttributeInternal(BROPENREQHEADERFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrOpenReqHeaderFk.
     * @param value value to set the BrOpenReqHeaderFk
     */
    public void setBrOpenReqHeaderFk(Number value) {
        setAttributeInternal(BROPENREQHEADERFK, value);
    }

    /**
     * Gets the attribute value for Years, using the alias name Years.
     * @return the value of Years
     */
    public Number getYears() {
        return (Number) getAttributeInternal(YEARS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Years.
     * @param value value to set the Years
     */
    public void setYears(Number value) {
        setAttributeInternal(YEARS, value);
    }

    /**
     * Gets the attribute value for UserIdFk, using the alias name UserIdFk.
     * @return the value of UserIdFk
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserIdFk.
     * @param value value to set the UserIdFk
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for EnterDate, using the alias name EnterDate.
     * @return the value of EnterDate
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnterDate.
     * @param value value to set the EnterDate
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for Rh, using the alias name Rh.
     * @return the value of Rh
     */
    public Number getRh() {
        return (Number) getAttributeInternal(RH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rh.
     * @param value value to set the Rh
     */
    public void setRh(Number value) {
        setAttributeInternal(RH, value);
    }

    /**
     * Gets the attribute value for Zh, using the alias name Zh.
     * @return the value of Zh
     */
    public Number getZh() {
        return (Number) getAttributeInternal(ZH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Zh.
     * @param value value to set the Zh
     */
    public void setZh(Number value) {
        setAttributeInternal(ZH, value);
    }

    /**
     * Gets the attribute value for Sgh, using the alias name Sgh.
     * @return the value of Sgh
     */
    public Number getSgh() {
        return (Number) getAttributeInternal(SGH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sgh.
     * @param value value to set the Sgh
     */
    public void setSgh(Number value) {
        setAttributeInternal(SGH, value);
    }

    /**
     * Gets the attribute value for Gh, using the alias name Gh.
     * @return the value of Gh
     */
    public Number getGh() {
        return (Number) getAttributeInternal(GH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gh.
     * @param value value to set the Gh
     */
    public void setGh(Number value) {
        setAttributeInternal(GH, value);
    }

    /**
     * Gets the attribute value for Buh, using the alias name Buh.
     * @return the value of Buh
     */
    public Number getBuh() {
        return (Number) getAttributeInternal(BUH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Buh.
     * @param value value to set the Buh
     */
    public void setBuh(Number value) {
        setAttributeInternal(BUH, value);
    }

    /**
     * Gets the attribute value for Uh, using the alias name Uh.
     * @return the value of Uh
     */
    public Number getUh() {
        return (Number) getAttributeInternal(UH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uh.
     * @param value value to set the Uh
     */
    public void setUh(Number value) {
        setAttributeInternal(UH, value);
    }

    /**
     * Gets the attribute value for Consultantans, using the alias name Consultantans.
     * @return the value of Consultantans
     */
    public Number getConsultantans() {
        return (Number) getAttributeInternal(CONSULTANTANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Consultantans.
     * @param value value to set the Consultantans
     */
    public void setConsultantans(Number value) {
        setAttributeInternal(CONSULTANTANS, value);
    }

    /**
     * Gets the attribute value for Total, using the alias name Total.
     * @return the value of Total
     */
    public Number getTotal() {
        return (Number) getAttributeInternal(TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Total.
     * @param value value to set the Total
     */
    public void setTotal(Number value) {
        setAttributeInternal(TOTAL, value);
    }

    /**
     * @return the associated entity DssBranchOpenReqHeaderImpl.
     */
    public DssBranchOpenReqHeaderImpl getDssBranchOpenReqHeader() {
        return (DssBranchOpenReqHeaderImpl) getAttributeInternal(DSSBRANCHOPENREQHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity DssBranchOpenReqHeaderImpl.
     */
    public void setDssBranchOpenReqHeader(DssBranchOpenReqHeaderImpl value) {
        setAttributeInternal(DSSBRANCHOPENREQHEADER, value);
    }


    /**
     * @param brOpenReqLineIdPk key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number brOpenReqLineIdPk) {
        return new Key(new Object[] { brOpenReqLineIdPk });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
      protected void create(AttributeList attributeList) {
          super.create(attributeList);
          Date currentDate = new Date();
          setEnterDate((Date) currentDate.getCurrentDate());
          setLastUpdatedDate((Date) currentDate.getCurrentDate());
          SequenceImpl seq = new SequenceImpl("dss_branch_open_req_line_seq", getDBTransaction());
          setBrOpenReqLineIdPk(seq.getSequenceNumber());
          
//          setBranchStatus("INCOMPLETE");
//          setDssStatus("INCOMPLETE");
          
          FacesContext fctx = FacesContext.getCurrentInstance();
          ExternalContext ectx = fctx.getExternalContext();
          HttpSession userSession = (HttpSession) ectx.getSession(false);
          try {
              setUserIdFk(new Number(userSession.getAttribute("pUserId")));
              setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
          } catch (SQLException ex) {
              setUserIdFk(new Number(0));
              setLastUpdatedBy(new Number(0));
          }
      }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Date currentDate = new Date();
        if (operation == DML_UPDATE) {
            setLastUpdatedDate((Date) currentDate.getCurrentDate());
            FacesContext fctx = FacesContext.getCurrentInstance();
            ExternalContext ectx = fctx.getExternalContext();
            HttpSession userSession = (HttpSession) ectx.getSession(false);
            try {
                setUserIdFk(new Number(userSession.getAttribute("pUserId")));
                setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
            } catch (SQLException ex) {
                setUserIdFk(new Number(0));
                setLastUpdatedBy(new Number(0));
            }
        }
        super.doDML(operation, e);
    }
}

