package pqt.dss.bor.model.vo;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;

import pqt.dss.bor.model.eo.DssBranchOpenReqLineDtlImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 28 17:24:31 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssBranchOpenReqLineDtlViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_DSSBRANCHOPENREQLINEDTL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BrOpenReqLineDtlPk,
        BrOpenReqHeaderFk,
        Name,
        Designation,
        ValidationTarget,
        Qtr1,
        Qtr2,
        Qtr3,
        Qtr4,
        Total,
        UserIdFk,
        EnterDate,
        LastUpdatedBy,
        LastUpdatedDate;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BROPENREQLINEDTLPK = AttributesEnum.BrOpenReqLineDtlPk.index();
    public static final int BROPENREQHEADERFK = AttributesEnum.BrOpenReqHeaderFk.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int DESIGNATION = AttributesEnum.Designation.index();
    public static final int VALIDATIONTARGET = AttributesEnum.ValidationTarget.index();
    public static final int QTR1 = AttributesEnum.Qtr1.index();
    public static final int QTR2 = AttributesEnum.Qtr2.index();
    public static final int QTR3 = AttributesEnum.Qtr3.index();
    public static final int QTR4 = AttributesEnum.Qtr4.index();
    public static final int TOTAL = AttributesEnum.Total.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssBranchOpenReqLineDtlViewRowImpl() {
    }

    /**
     * Gets DssBranchOpenReqLineDtl entity object.
     * @return the DssBranchOpenReqLineDtl
     */
    public DssBranchOpenReqLineDtlImpl getDssBranchOpenReqLineDtl() {
        return (DssBranchOpenReqLineDtlImpl) getEntity(ENTITY_DSSBRANCHOPENREQLINEDTL);
    }

    /**
     * Gets the attribute value for BR_OPEN_REQ_LINE_DTL_PK using the alias name BrOpenReqLineDtlPk.
     * @return the BR_OPEN_REQ_LINE_DTL_PK
     */
    public Number getBrOpenReqLineDtlPk() {
        return (Number) getAttributeInternal(BROPENREQLINEDTLPK);
    }

    /**
     * Sets <code>value</code> as attribute value for BR_OPEN_REQ_LINE_DTL_PK using the alias name BrOpenReqLineDtlPk.
     * @param value value to set the BR_OPEN_REQ_LINE_DTL_PK
     */
    public void setBrOpenReqLineDtlPk(Number value) {
        setAttributeInternal(BROPENREQLINEDTLPK, value);
    }

    /**
     * Gets the attribute value for BR_OPEN_REQ_HEADER_FK using the alias name BrOpenReqHeaderFk.
     * @return the BR_OPEN_REQ_HEADER_FK
     */
    public Number getBrOpenReqHeaderFk() {
        return (Number) getAttributeInternal(BROPENREQHEADERFK);
    }

    /**
     * Sets <code>value</code> as attribute value for BR_OPEN_REQ_HEADER_FK using the alias name BrOpenReqHeaderFk.
     * @param value value to set the BR_OPEN_REQ_HEADER_FK
     */
    public void setBrOpenReqHeaderFk(Number value) {
        setAttributeInternal(BROPENREQHEADERFK, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for DESIGNATION using the alias name Designation.
     * @return the DESIGNATION
     */
    public String getDesignation() {
        return (String) getAttributeInternal(DESIGNATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESIGNATION using the alias name Designation.
     * @param value value to set the DESIGNATION
     */
    public void setDesignation(String value) {
        setAttributeInternal(DESIGNATION, value);
    }

    /**
     * Gets the attribute value for VALIDATION_TARGET using the alias name ValidationTarget.
     * @return the VALIDATION_TARGET
     */
    public Number getValidationTarget() {
        return (Number) getAttributeInternal(VALIDATIONTARGET);
    }

    /**
     * Sets <code>value</code> as attribute value for VALIDATION_TARGET using the alias name ValidationTarget.
     * @param value value to set the VALIDATION_TARGET
     */
    public void setValidationTarget(Number value) {
        setAttributeInternal(VALIDATIONTARGET, value);
    }

    /**
     * Gets the attribute value for QTR_1 using the alias name Qtr1.
     * @return the QTR_1
     */
    public Number getQtr1() {
        return (Number) getAttributeInternal(QTR1);
    }

    /**
     * Sets <code>value</code> as attribute value for QTR_1 using the alias name Qtr1.
     * @param value value to set the QTR_1
     */
    public void setQtr1(Number value) {
        Number oldQtr = getQtr1() == null ? new Number(0) : getQtr1();
        Number newQtr = value == null ? new Number(0) : value;
        Number oldTotal = getTotal() == null ? new Number(0) : getTotal();
        Number newTotal = oldTotal.subtract(oldQtr).add(newQtr);
        setTotal(newTotal);
        
        setAttributeInternal(QTR1, value);
    }

    /**
     * Gets the attribute value for QTR_2 using the alias name Qtr2.
     * @return the QTR_2
     */
    public Number getQtr2() {
        return (Number) getAttributeInternal(QTR2);
    }

    /**
     * Sets <code>value</code> as attribute value for QTR_2 using the alias name Qtr2.
     * @param value value to set the QTR_2
     */
    public void setQtr2(Number value) {
        Number oldQtr = getQtr2() == null ? new Number(0) : getQtr2();
        Number newQtr = value == null ? new Number(0) : value;
        Number oldTotal = getTotal() == null ? new Number(0) : getTotal();
        Number newTotal = oldTotal.subtract(oldQtr).add(newQtr);
        setTotal(newTotal);
        
        setAttributeInternal(QTR2, value);
    }

    /**
     * Gets the attribute value for QTR_3 using the alias name Qtr3.
     * @return the QTR_3
     */
    public Number getQtr3() {
        return (Number) getAttributeInternal(QTR3);
    }

    /**
     * Sets <code>value</code> as attribute value for QTR_3 using the alias name Qtr3.
     * @param value value to set the QTR_3
     */
    public void setQtr3(Number value) {
        Number oldQtr = getQtr3() == null ? new Number(0) : getQtr3();
        Number newQtr = value == null ? new Number(0) : value;
        Number oldTotal = getTotal() == null ? new Number(0) : getTotal();
        Number newTotal = oldTotal.subtract(oldQtr).add(newQtr);
        setTotal(newTotal);
        
        setAttributeInternal(QTR3, value);
    }

    /**
     * Gets the attribute value for QTR_4 using the alias name Qtr4.
     * @return the QTR_4
     */
    public Number getQtr4() {
        return (Number) getAttributeInternal(QTR4);
    }

    /**
     * Sets <code>value</code> as attribute value for QTR_4 using the alias name Qtr4.
     * @param value value to set the QTR_4
     */
    public void setQtr4(Number value) {
        Number oldQtr = getQtr4() == null ? new Number(0) : getQtr4();
        Number newQtr = value == null ? new Number(0) : value;
        Number oldTotal = getTotal() == null ? new Number(0) : getTotal();
        Number newTotal = oldTotal.subtract(oldQtr).add(newQtr);
        setTotal(newTotal);
        
        setAttributeInternal(QTR4, value);
    }


    /**
     * Gets the attribute value for TOTAL using the alias name Total.
     * @return the TOTAL
     */
    public Number getTotal() {
        return (Number) getAttributeInternal(TOTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL using the alias name Total.
     * @param value value to set the TOTAL
     */
    public void setTotal(Number value) {
        setAttributeInternal(TOTAL, value);
    }

    /**
     * Gets the attribute value for USER_ID_FK using the alias name UserIdFk.
     * @return the USER_ID_FK
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID_FK using the alias name UserIdFk.
     * @param value value to set the USER_ID_FK
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for ENTER_DATE using the alias name EnterDate.
     * @return the ENTER_DATE
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTER_DATE using the alias name EnterDate.
     * @param value value to set the ENTER_DATE
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }
}

