package pqt.dss.bor.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 30 17:15:38 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssBranchOpenReqLineDtlViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DssBranchOpenReqLineDtlViewImpl() {
    }
}

